from fastapi import APIRouter, Depends, HTTPException

router = APIRouter(prefix="/v1", tags=["generate"])


@router.post("/generate", response_model=dict)
async def generate_description(request: dict):
    return {"title": "Product", "description": "Description generated by AI"}
